// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/todos/[id].ts";
import * as $3 from "./routes/api/todos/index.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/trpc/[...path].ts";
import * as $$0 from "./islands/AddTodo.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/DeleteTodo.tsx";
import * as $$3 from "./islands/TodoItem.tsx";
import * as $$4 from "./islands/TodoList.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/todos/[id].ts": $2,
    "./routes/api/todos/index.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/trpc/[...path].ts": $5,
  },
  islands: {
    "./islands/AddTodo.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/DeleteTodo.tsx": $$2,
    "./islands/TodoItem.tsx": $$3,
    "./islands/TodoList.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
